channels:
  - bioconda
  - conda-forge
  - r
  - rdonnelly

dependencies:
- bioconductor-biocgenerics=0.34.0
- bioconductor-graph=1.66.0
- bioconductor-org.hs.eg.db=3.11.4
- bioconductor-piano=2.4.0
- bioconductor-rcy3=2.8.0
- bioconductor-tcgabiolinks=2.16.0
- cytoscape=3.7.2
- glpk=4.57
- gseapy=0.10.3
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.1
- leidenalg=0.8.3
- matplotlib=3.3.4
- nb_conda_kernels=2.3.1
- numpy=1.20.1
- pandas=1.2.3
- pip=21.0.1
- pycairo=1.20.0
- python-igraph=0.8.3
- python=3.9.2
- r-base=4.0.2
- r-circlize=0.4.12
- r-ggplot2=3.3.3
- r-httr=1.4.2
- r-igraph=1.2.6
- r-janitor=2.1.0
- r-pheatmap=1.0.12
- r-r.utils=2.10.1
- r-rjsonio=1.3_1.4
- r-tidyr=1.1.2
- r-tidyverse=1.3.0
- r-xml=3.99_0.5
- rstudio=1.1.456
- scikit-learn=0.24.1
- scipy=1.5.3
- seaborn=0.11.1
